import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import API from '../api/axios';

const AIGuidance = () => {
  const navigate = useNavigate();
  const [selectedTopic, setSelectedTopic] = useState(0);
  const [aiReport, setAiReport] = useState('');
  const [loadingAI, setLoadingAI] = useState(false);

  const weeklyReports = [
    {
      week: 'Week 1', title: 'Understanding Type 1 Diabetes', icon: '📚',
      content: [
        { heading: 'What is Type 1 Diabetes?', text: 'Type 1 diabetes is an autoimmune condition where the pancreas produces little or no insulin. Insulin is a hormone needed to allow glucose to enter cells to produce energy.' },
        { heading: 'Why Insulin is Important', text: 'Without insulin, glucose builds up in the bloodstream instead of being used for energy. This is why people with Type 1 diabetes need to take insulin every day.' },
        { heading: 'Blood Glucose Monitoring', text: 'Regular blood glucose monitoring helps you understand how food, activity, and insulin affect your blood sugar levels.' }
      ]
    },
    {
      week: 'Week 2', title: 'Carbohydrates & Blood Sugar', icon: '🍎',
      content: [
        { heading: 'How Carbs Affect Blood Sugar', text: 'Carbohydrates have the greatest impact on blood glucose levels. When you eat carbs, your body breaks them down into glucose, which enters your bloodstream.' },
        { heading: 'Carb Counting', text: 'Carb counting is a meal planning technique that helps manage blood glucose. By knowing how many carbs are in your food, you can calculate the right insulin dose.' },
        { heading: 'Glycemic Index', text: 'The glycemic index (GI) measures how quickly foods raise blood sugar. Low GI foods like vegetables and whole grains raise blood sugar slowly.' }
      ]
    },
    {
      week: 'Week 3', title: 'Exercise & Diabetes', icon: '🏃',
      content: [
        { heading: 'Benefits of Exercise', text: 'Regular physical activity helps lower blood glucose levels, improves insulin sensitivity, and helps maintain a healthy weight.' },
        { heading: 'Before Exercise', text: 'Always check your blood glucose before exercising. If it is below 100 mg/dL, eat a small carbohydrate snack before starting.' },
        { heading: 'After Exercise', text: 'Exercise can lower blood glucose for up to 24 hours after activity. Monitor your glucose more frequently after exercise.' }
      ]
    },
    {
      week: 'Week 4', title: 'Managing Hypoglycemia', icon: '⚠️',
      content: [
        { heading: 'What is Hypoglycemia?', text: 'Hypoglycemia occurs when blood glucose falls below 70 mg/dL. Symptoms include shakiness, sweating, confusion, and rapid heartbeat.' },
        { heading: 'The 15-15 Rule', text: 'If your blood sugar is low, eat 15 grams of fast-acting carbohydrates, wait 15 minutes, then check again. Repeat if still low.' },
        { heading: 'Prevention', text: 'Prevent hypoglycemia by eating regular meals, not skipping meals, and always carrying a fast-acting sugar source with you.' }
      ]
    }
  ];

  const tips = [
    { icon: '💧', tip: 'Stay hydrated — drink 8 glasses of water daily' },
    { icon: '😴', tip: 'Get 7-8 hours of sleep — poor sleep affects blood sugar' },
    { icon: '🧘', tip: 'Manage stress — stress hormones raise blood glucose' },
    { icon: '👟', tip: 'Walk for 30 minutes daily to improve insulin sensitivity' },
    { icon: '🥗', tip: 'Eat balanced meals with protein, healthy fats and complex carbs' },
    { icon: '📱', tip: 'Log every reading — patterns help your doctor adjust treatment' }
  ];

  const generateAIReport = async () => {
    setLoadingAI(true);
    setAiReport('');
    try {
      const res = await API.get('/ai/weekly-report');
      setAiReport(res.data.report);
    } catch (err) {
      setAiReport('Unable to generate report at this time. Please try again later.');
    }
    setLoadingAI(false);
  };

  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <h1 style={styles.logo}>DiaGuide</h1>
        <button style={styles.backBtn} onClick={() => navigate('/dashboard')}>← Dashboard</button>
      </div>

      <div style={styles.content}>
        <h2 style={styles.title}>🤖 AI Educational Guidance</h2>
        <p style={styles.subtitle}>Weekly educational reports to help you better understand and manage Type 1 Diabetes</p>

        <div style={styles.disclaimer}>
          ⚕️ This content is for <strong>educational purposes only</strong> and does not replace personalized medical advice from your doctor.
        </div>

        <div style={styles.aiCard}>
          <h3 style={styles.aiTitle}>✨ AI Weekly Report</h3>
          <p style={styles.aiSubtitle}>Get a personalized educational report generated by AI</p>
          <button style={styles.aiBtn} onClick={generateAIReport} disabled={loadingAI}>
            {loadingAI ? '⏳ Generating report...' : '🤖 Generate Weekly Report'}
          </button>
          {aiReport && (
            <div style={styles.aiReport}>
              <p style={styles.aiReportText}>{aiReport}</p>
            </div>
          )}
        </div>

        <h3 style={styles.sectionTitle}>📅 Weekly Educational Reports</h3>
        <div style={styles.tabRow}>
          {weeklyReports.map((report, i) => (
            <button key={i}
              style={selectedTopic === i ? styles.tabActive : styles.tab}
              onClick={() => setSelectedTopic(i)}>
              {report.icon} {report.week}
            </button>
          ))}
        </div>

        <div style={styles.reportCard}>
          <h3 style={styles.reportTitle}>{weeklyReports[selectedTopic].icon} {weeklyReports[selectedTopic].title}</h3>
          {weeklyReports[selectedTopic].content.map((item, i) => (
            <div key={i} style={styles.reportSection}>
              <h4 style={styles.reportHeading}>{item.heading}</h4>
              <p style={styles.reportText}>{item.text}</p>
            </div>
          ))}
        </div>

        <h3 style={styles.sectionTitle}>💡 Daily Health Tips</h3>
        <div style={styles.tipsGrid}>
          {tips.map((t, i) => (
            <div key={i} style={styles.tipCard}>
              <span style={styles.tipIcon}>{t.icon}</span>
              <p style={styles.tipText}>{t.tip}</p>
            </div>
          ))}
        </div>

        <div style={styles.bottomDisclaimer}>
          ⚕️ Always follow your doctor's personalized advice. This educational content is based on general diabetes management guidelines and does not constitute medical advice.
        </div>
      </div>
    </div>
  );
};

const styles = {
  container: { minHeight: '100vh', backgroundColor: '#f0f4f8', fontFamily: "'Segoe UI', Arial, sans-serif" },
  header: {
    background: 'linear-gradient(90deg, #1E3A5F, #2d5a8e)',
    padding: '16px 32px', display: 'flex', justifyContent: 'space-between', alignItems: 'center'
  },
  logo: { color: '#ff7f50', fontSize: '24px', margin: 0, fontWeight: '800' },
  backBtn: {
    padding: '8px 16px', backgroundColor: 'transparent',
    color: '#ff7f50', border: '1px solid #ff7f50', borderRadius: '8px', cursor: 'pointer'
  },
  content: { padding: '32px', maxWidth: '900px', margin: '0 auto' },
  title: { color: '#ff7f50', marginBottom: '8px', fontWeight: '700' },
  subtitle: { color: '#6B7280', marginBottom: '24px' },
  disclaimer: {
    backgroundColor: '#FFF5F0', border: '1px solid #FFD4C2',
    borderRadius: '8px', padding: '12px 16px', marginBottom: '32px', color: '#ff7f50'
  },
  aiCard: {
    backgroundColor: 'white', padding: '24px', borderRadius: '12px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)', marginBottom: '32px',
    border: '1px solid #FFD4C2'
  },
  aiTitle: { color: '#ff7f50', marginBottom: '8px', fontWeight: '700' },
  aiSubtitle: { color: '#6B7280', marginBottom: '16px' },
  aiBtn: {
    padding: '12px 24px',
    background: 'linear-gradient(90deg, #ff7f50, #ff6030)',
    color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '15px', fontWeight: '600'
  },
  aiReport: {
    marginTop: '20px', backgroundColor: '#FFF5F0', padding: '20px',
    borderRadius: '8px', borderLeft: '4px solid #ff7f50'
  },
  aiReportText: { color: '#374151', lineHeight: '1.8', margin: 0, whiteSpace: 'pre-wrap' },
  sectionTitle: { color: '#ff7f50', marginBottom: '16px', fontWeight: '700' },
  tabRow: { display: 'flex', gap: '8px', marginBottom: '16px', flexWrap: 'wrap' },
  tab: {
    padding: '8px 16px', backgroundColor: 'white', border: '1px solid #E5E7EB',
    borderRadius: '8px', cursor: 'pointer', color: '#6B7280'
  },
  tabActive: {
    padding: '8px 16px',
    background: 'linear-gradient(90deg, #ff7f50, #ff6030)',
    border: 'none', borderRadius: '8px', cursor: 'pointer', color: 'white', fontWeight: '600'
  },
  reportCard: {
    backgroundColor: 'white', padding: '24px', borderRadius: '12px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)', marginBottom: '32px'
  },
  reportTitle: { color: '#ff7f50', marginBottom: '20px', fontSize: '20px', fontWeight: '700' },
  reportSection: { marginBottom: '20px', paddingBottom: '20px', borderBottom: '1px solid #F3F4F6' },
  reportHeading: { color: '#374151', marginBottom: '8px' },
  reportText: { color: '#6B7280', lineHeight: '1.6', margin: 0 },
  tipsGrid: {
    display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
    gap: '16px', marginBottom: '32px'
  },
  tipCard: {
    backgroundColor: 'white', padding: '16px', borderRadius: '12px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)', display: 'flex', alignItems: 'center', gap: '12px'
  },
  tipIcon: { fontSize: '28px' },
  tipText: { color: '#374151', margin: 0, fontSize: '14px' },
  bottomDisclaimer: {
    backgroundColor: '#FFF5F0', padding: '16px', borderRadius: '8px',
    color: '#ff7f50', fontSize: '14px', border: '1px solid #FFD4C2'
  }
};

export default AIGuidance;